#!/bin/sh

[[ $USER == "root" ]] && (echo "Don't run as root."; exit 1)

[[ ! -f README.roff ]] && (echo "Can't find README.roff"; exit 1)
[[ -f README.dvi ]] && (echo "WARNING: typeset DVI file already exists. \
Overwriting now.")

echo -e "\nWe need: groff, preconv, and optionally xdvi. Checking if they're all there."

echo -e "\nHello, groff. Are you there?"
groff -v
if [ $? != 0 ]; then
    echo "Can't find groff!"
    exit 1
fi

echo -e "\nHello, preconv. Are you there?"
preconv -v
if [ $? != 0 ]; then
    echo "Can't find preconv!"
    exit 1
fi

echo -e "\nHello, xdvi. Are you there?"
xdvi -v
XDVIRET=$?
if [ $XDVIRET != 0 ]; then
    echo "Can't find xdvi"
fi

echo -e "\n\nCompiling documents now."

if [ $XDVIRET != 0 ]; then
    echo "WARNING: xdvi is absent! Typesetting to TTY instead."
    groff -Tutf8 -Kutf8 README.roff | less
else
    groff -Tdvi -Kutf8 README.roff > README.dvi
    xdvi README.dvi
fi
